Add initialization to bookkeeper

diff --git a/bookkeeper b/bookkeeper
--- a/bookkeeper
+++ b/bookkeeper
@@ -66,12 +66,55 @@ CMD=$(cat<<EOF
 EOF
 )
 
+[ -z "${CLUSTER_NAME}" ] && CLUSTER_NAME=bookkeeper
+
+[ -z "${STREAM_STORAGE_ROOT_PATH}" ] && STREAM_STORAGE_ROOT_PATH="${CLUSTER_NAME}/stream"
+
+# Where Zookeeper is
+METADATA_URI=$(grep BK_metadataServiceUri /conf/bookkeeper.conf | cut -d'=' -f2 | tr -d ' ')
+
+
+ZK_HOST=$(echo "${METADATA_URI}" | egrep -o '([0-9]{1,3}\.){3}([0-9]{1,3}):[0-9]*')
+
+# The longest time in seconds to wait on a peer to init the cluster before giving up
+[ -z "${MAX_INIT_WAIT}" ] && MAX_INIT_WAIT=100
+
+# Init the cluster if we havent
+if ! ${CMD} org.apache.zookeeper.ZooKeeperMain -server ${ZK_HOST} stat ${STREAM_STORAGE_ROOT_PATH}; then
+  echo "${STREAM_STORAGE_ROOT_PATH} does not exist in Zookeeper ${ZK_HOST}. We will try to initialize...."
+  # If we can create this ephemeral node then we know that another node hasn't and we are the first to try and do an init
+  if ${CMD} org.apache.zookeeper.ZooKeeperMain -server ${ZK_HOST} create -e ${CLUSTER_NAME}/bkInitLock; then
+    echo "Got a lock. Running init now........"
+    if ${CMD} org.apache.bookkeeper.tools.cli.BKCtl --conf /conf/bookkeeper.conf --service-uri ${METADATA_URI} cluster init; then
+      echo "Init finished..."
+    else
+      echo "Init failed. Exiting..."
+      exit 2
+    fi
+  else
+    # If we couldn't write to that node then there must be a peer that did. Lets wait on them to finish initializing
+    echo "Could not get a lock on bkInitLock. Waiting on peer to initialize cluster"
+    N=1
+    while ! ${CMD} org.apache.zookeeper.ZooKeeperMain -server ${ZK_HOST} stat ${STREAM_STORAGE_ROOT_PATH}; do
+      echo "Waiting on peer to init cluster......"
+      sleep 5
+      ((N++))
+      if [ "$N" -gt "${MAX_INIT_WAIT}" ]; then
+        echo "Gave up on initializing after ${MAX_INIT_WAIT} seconds"
+        exit 2
+      fi
+    done
+  fi
+else
+  echo "Cluster is already initialized. Going on with our lives"
+fi
+
 # For autorecovery we have to run two separate processes
 if [ -z "${DISABLE_AUTORECOVERY}" ]; then
-  $CMD org.apache.bookkeeper.server.Main --conf /conf/bookkeeper.conf &
+  ${CMD} org.apache.bookkeeper.server.Main --conf /conf/bookkeeper.conf &
   MAIN_PID="$!"
 
-  $CMD org.apache.bookkeeper.replication.AutoRecoveryMain --conf /conf/bookkeeper.conf &
+  ${CMD} org.apache.bookkeeper.replication.AutoRecoveryMain --conf /conf/bookkeeper.conf &
   RECOVERY_PID="$!"
   # exit if either one fails
   while true; do
@@ -87,10 +130,5 @@ if [ -z "${DISABLE_AUTORECOVERY}" ]; then
   done
 else
   # Only one process so we will stay in the foreground
-  $CMD org.apache.bookkeeper.server.Main --conf /conf/bookkeeper.conf
+  ${CMD} org.apache.bookkeeper.server.Main --conf /conf/bookkeeper.conf
 fi
-
-
-## Run on start
-elif [ ${COMMAND} == "upgrade" ]; then
-  exec ${JAVA} ${OPTS} org.apache.bookkeeper.bookie.FileSystemUpgrade --conf ${BOOKIE_CONF} $@
