Add shell, bkctl, autorecovery, usage, dlog, and dlog admin features as args

diff --git a/bookkeeper b/bookkeeper
--- a/bookkeeper
+++ b/bookkeeper
@@ -1,4 +1,19 @@
 #!/bin/bash
+function usage(){
+  cat<<EOF
+
+    Command: bookkeeper [ -s | -b | -a | -c ]
+
+    Options:
+      -shell         Run bookkeeper shell
+      -bookie        Start a bookie
+      -autorecovery  Run the autorecovery process
+      -bkctl         Run bkCtl
+      -dlog          Run dlog
+      -dadmin        Run dlog admin
+
+EOF
+}
 
 JAVA=$(which java)
 
@@ -70,60 +85,94 @@ METADATA_URI=$(grep metadataServiceUri /conf/bookkeeper.conf | cut -d'=' -f2 | t
 # Basically the same as METADATA_URI, just without the protocol. FYI we don't support zkServers list since it is deprecated
 ZK_HOST=$(echo "${METADATA_URI}" | sed -r 's#.*//(.*:[0-9]+).*#\1#')
 
-echo "Zookeeper host endpoint is $ZK_HOST"
 
 # The longest time in seconds to wait on a peer to init the cluster before giving up
 [ -z "${MAX_INIT_WAIT}" ] && MAX_INIT_WAIT=100
 
-# Init the cluster if we havent
-if ${CMD} org.apache.zookeeper.ZooKeeperMain -server ${ZK_HOST} stat /${CLUSTER_NAME}/ledgers 2>&1 | grep -q "Node does not exist:"; then
-  echo "${CLUSTER_NAME}/ledgers does not exist in Zookeeper ${ZK_HOST}. We will try to initialize...."
-  # If we can create this ephemeral node then we know that another node hasn't and we are the first to try and do an init
-  if ! ${CMD} org.apache.zookeeper.ZooKeeperMain -server ${ZK_HOST} create -e /${CLUSTER_NAME}-bkInitLock locked 2>&1 | grep -q 'Node already exists:'; then
-    echo "Got a lock. Running init now........"
-    if ${CMD} org.apache.bookkeeper.tools.cli.BKCtl --conf /conf/bookkeeper.conf cluster init -x ${CLUSTER_NAME} zk+hierarchical://${ZK_HOST}; then
-     echo "Init finished..."
-    else
-      echo "Init failed. Exiting..."
-      exit 2
-    fi
-  else
-    # If we couldn't write to that node then there must be a peer that did. Lets wait on them to finish initializing
-    echo "Could not get a lock on bkInitLock. Waiting on peer to initialize cluster"
-    N=1
-    while ${CMD} org.apache.zookeeper.ZooKeeperMain -server ${ZK_HOST} stat ${STREAM_STORAGE_ROOT_PATH} 2>&1 | grep -q "Node does not exist:"; do
-      echo "Waiting on peer to init cluster......"
-      sleep 5
-      ((N++))
-      if [ "$N" -gt "${MAX_INIT_WAIT}" ]; then
-        echo "Gave up on initializing after ${MAX_INIT_WAIT} seconds"
+function _init(){
+  echo "Zookeeper host endpoint is $ZK_HOST"
+  # Init the cluster if we havent
+  if ${CMD} org.apache.zookeeper.ZooKeeperMain -server ${ZK_HOST} stat /${CLUSTER_NAME}/ledgers 2>&1 | grep -q "Node does not exist:"; then
+    echo "${CLUSTER_NAME}/ledgers does not exist in Zookeeper ${ZK_HOST}. We will try to initialize...."
+    # If we can create this ephemeral node then we know that another node hasn't and we are the first to try and do an init
+    if ! ${CMD} org.apache.zookeeper.ZooKeeperMain -server ${ZK_HOST} create -e /${CLUSTER_NAME}-bkInitLock locked 2>&1 | grep -q 'Node already exists:'; then
+      echo "Got a lock. Running init now........"
+      if ${CMD} org.apache.bookkeeper.tools.cli.BKCtl --conf /conf/bookkeeper.conf cluster init -x ${CLUSTER_NAME} zk+hierarchical://${ZK_HOST}; then
+       echo "Init finished..."
+      else
+        echo "Init failed. Exiting..."
         exit 2
       fi
-    done
+    else
+      # If we couldn't write to that node then there must be a peer that did. Lets wait on them to finish initializing
+      echo "Could not get a lock on bkInitLock. Waiting on peer to initialize cluster"
+      N=1
+      while ${CMD} org.apache.zookeeper.ZooKeeperMain -server ${ZK_HOST} stat ${STREAM_STORAGE_ROOT_PATH} 2>&1 | grep -q "Node does not exist:"; do
+        echo "Waiting on peer to init cluster......"
+        sleep 5
+        ((N++))
+        if [ "$N" -gt "${MAX_INIT_WAIT}" ]; then
+          echo "Gave up on initializing after ${MAX_INIT_WAIT} seconds"
+          exit 2
+        fi
+      done
+    fi
+  else
+    echo "Cluster is already initialized. Going on with our lives"
   fi
-else
-  echo "Cluster is already initialized. Going on with our lives"
-fi
+}
 
-
-if [ -z "${AUTO_RECOVERY}" ]; then
-  cat<<EOF
-    ##############################################################################################
-    #                                                                                            #
-    #                                 Starting Bookie                                            #
-    #                                                                                            #
-    ##############################################################################################
+case ${1} in
+  -shell)
+    # Bookkeeper shell
+    shift
+    ENTRY_FORMATTER_ARG="-DentryFormatterClass=${ENTRY_FORMATTER_CLASS:-org.apache.bookkeeper.util.StringEntryFormatter}"
+    exec ${CMD} ${ENTRY_FORMATTER_ARG} org.apache.bookkeeper.bookie.BookieShell -conf /conf/bookkeeper.conf $@
+    exit
+    ;;
+  -bookie)
+    # Start bookkeeper bookie
+    cat<<EOF
+      ##############################################################################################
+      #                                                                                            #
+      #                                 Starting Bookie                                            #
+      #                                                                                            #
+      ##############################################################################################
 EOF
-
-  ${CMD} org.apache.bookkeeper.server.Main --conf /conf/bookkeeper.conf
-else
-  cat<<EOF
-    ##############################################################################################
-    #                                                                                            #
-    #                                 Starting Autorecovery daemon                               #
-    #                                                                                            #
-    ##############################################################################################
+    _init
+    ${CMD} org.apache.bookkeeper.server.Main --conf /conf/bookkeeper.conf
+    exit
+    ;;
+  -autorecovery)
+    # Start the autorecovery daemon
+    cat<<EOF
+      ##############################################################################################
+      #                                                                                            #
+      #                                 Starting Autorecovery daemon                               #
+      #                                                                                            #
+      ##############################################################################################
 EOF
-
-  ${CMD} org.apache.bookkeeper.replication.AutoRecoveryMain --conf /conf/bookkeeper.conf
-fi
+    _init
+    ${CMD} org.apache.bookkeeper.replication.AutoRecoveryMain --conf /conf/bookkeeper.conf
+    exit
+    ;;
+  -bkctl)
+  # Run bkctl
+  shift
+  cd /bookkeeper
+  ${CMD}org.apache.bookkeeper.tools.cli.BKCtl --conf /conf/bookkeeper.conf $@
+  exit
+  ;;
+  -dlog)
+    exec ${CMD} org.apache.distributedlog.tools.Tool org.apache.distributedlog.tools.DistributedLogTool $@
+    exit
+    ;;
+  -dadmin)
+    ${CMD} org.apache.distributedlog.tools.Tool org.apache.distributedlog.admin.DistributedLogAdmin $@
+    exit
+    ;;
+  *)
+    usage
+    exit
+    ;;
+esac
